### ISSUE TITLE
sass/scss 文件 class name 提取

### ISSUE THREAD

**Issue by NewFuture** [wx-minapp/minapp-vscode#33]
scss 嵌套写法不能提取全部class
```scss
.a{
  color: #fff;
  &-b{
    color: #aaa;
  }
}
```
现在好像是正则提取的
https://github.com/wx-minapp/minapp-vscode/blob/167d33c11e7c61ff942cfe960249aa0dcb96d973/src/plugin/lib/quickParseStle.ts#L4

只能提取到`.a`,无法提取到 `.a-b`
