### ISSUE TITLE
wxml 格式化自动在首字符插入分号

### ISSUE THREAD

**Issue by HualiangLI** [wx-minapp/minapp-vscode#66]
# VSC 信息
```yaml
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

# wxml 文件内容
```jsx
<view class="comp__profile">
  <image class="img-profile" src="{{ profilePic }}" />
  <text class="text-name">{{ name }}</text>
  <view class="btn-edit" bind:tap="onEdit" wx:if="{{ isLogin }}">
    <text class="iconfont icon-Edit" />
    <text class="btn-text">编辑</text>
  </view>
</view>
```

Format 后，会在文件首第一行第一列插入 `;`
